CREATE TABLE lyfter_car_rental.cars (
    id                  SERIAL PRIMARY KEY,
    brand               VARCHAR(50) NOT NULL,
    model               VARCHAR(100) NOT NULL,
    manufacture_year    INTEGER NOT NULL,
    status              VARCHAR(30) NOT NULL
);

INSERT INTO lyfter_car_rental.cars (brand, model, manufacture_year, status) VALUES
('Toyota', 'Corolla', 2022, 'disponible'),
('Honda', 'Civic', 2023, 'disponible'),
('Volkswagen', 'Golf', 2021, 'rentado'),
('Ford', 'Focus', 2022, 'disponible'),
('Chevrolet', 'Spark', 2020, 'mantenimiento'),
('Hyundai', 'Elantra', 2023, 'disponible'),
('Kia', 'Rio', 2021, 'disponible'),
('Nissan', 'Sentra', 2022, 'reservado'),
('Mazda', 'Mazda3', 2023, 'disponible'),
('Renault', 'Clio', 2021, 'disponible'),
('Peugeot', '208', 2022, 'rentado'),
('Fiat', 'Argo', 2020, 'disponible'),
('Seat', 'Ibiza', 2023, 'disponible'),
('Toyota', 'Yaris', 2021, 'disponible'),
('Honda', 'Fit', 2022, 'mantenimiento'),
('Volkswagen', 'Polo', 2023, 'disponible'),
('Ford', 'Fiesta', 2019, 'fuera_de_servicio'),
('Hyundai', 'i20', 2022, 'disponible'),
('Kia', 'Cerato', 2021, 'rentado'),
('Nissan', 'Versa', 2023, 'disponible'),
('Toyota', 'Camry', 2022, 'disponible'),
('Honda', 'Accord', 2021, 'disponible'),
('Volkswagen', 'Passat', 2023, 'reservado'),
('BMW', 'Serie 3', 2022, 'disponible'),
('Mercedes-Benz', 'Clase C', 2021, 'rentado'),
('Audi', 'A3', 2023, 'disponible'),
('Chevrolet', 'Cruze', 2020, 'disponible'),
('Mazda', 'Mazda6', 2022, 'disponible'),
('Toyota', 'RAV4', 2023, 'disponible'),
('Honda', 'CR-V', 2022, 'rentado'),
('Volkswagen', 'Tiguan', 2021, 'disponible'),
('Ford', 'Escape', 2023, 'disponible'),
('Hyundai', 'Tucson', 2022, 'mantenimiento'),
('Kia', 'Sportage', 2021, 'disponible'),
('Nissan', 'Kicks', 2023, 'disponible'),
('Jeep', 'Compass', 2022, 'disponible'),
('Mazda', 'CX-5', 2021, 'reservado'),
('Subaru', 'Forester', 2023, 'disponible'),
('Toyota', 'Hilux', 2022, 'rentado'),
('Ford', 'Ranger', 2021, 'disponible'),
('Chevrolet', 'Colorado', 2020, 'disponible'),
('Volkswagen', 'Amarok', 2023, 'disponible'),
('Renault', 'Duster', 2022, 'disponible'),
('Fiat', 'Toro', 2021, 'disponible'),
('Peugeot', '2008', 2023, 'disponible'),
('Toyota', 'Corolla Cross', 2022, 'disponible'),
('Honda', 'HR-V', 2021, 'rentado'),
('Volkswagen', 'Taos', 2023, 'disponible'),
('Ford', 'Bronco Sport', 2022, 'disponible');
